### ISSUE TITLE
Issue when the format of the video isn't .mp4

### ISSUE THREAD

**Issue by ceso** [fcr--/lua-openfing#5]
When I tried to watch a video of md1 (specific the class 03), the app throwed the following error:

Not Found	gstsouphttpsrc.c(1626): gst_soup_http_src_parse_status (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstSoupHTTPSrc:source:
Not Found (404), URL: http://openfing-video.fing.edu.uy/media/md1/md1_03.mp4, Redirect to: (NULL)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

Looking in firefox the same video with the help of the developer tools, I found that the error happens because the extension of the video isn't .mp4, instead, it is .webm, here is the response:

HTTP/1.1 206 Partial Content
Connection: keep-alive
Content-Length: 43746
Content-Range: bytes 238944256-238988001/238988002
Content-Type: video/webm
Date: Tue, 20 Mar 2018 04:50:16 GMT
ETag: "521bb102-e3eaae2"
Last-Modified: Mon, 26 Aug 2013 19:48:18 GMT
Server: nginx/1.10.2

For sure this isn't the only video in .webm, adding the possibility of reproducing either webm or mp4 in an automatized way could be good.

Regards!

**Comment by fcr--** [comment]
Since playbin does not support alternative uris, the implemented fix was not the cleanest one.  Specifically, once a Gst.ResourceError.NOT_FOUND is detected, the player catches the following error and retries with a different format.

Fixed in commit 525abc622bacab6b01da9c36c5da34d80f107acc. Thank you for finding the bug!
